# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [8]:
a = np.arange(11)
a[3:7] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [11]:
A = np.random.rand(3, 6)
print(A)

ans = len(A[A>0.5])
print(ans)

[[0.49415117 0.65112627 0.34486827 0.02671477 0.61449535 0.95831014]
 [0.2464544  0.6453798  0.09516505 0.4158571  0.62188051 0.36772275]
 [0.99401954 0.00673241 0.28218668 0.87776738 0.51965462 0.03355517]]
8
