# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [7]:
import numpy as np

a = np.random.randint(10, size = 6 )

print('list(a): ', list(a))
print('a.tolist(): ' ,a.tolist())

b = np.random.randint(10, size = 6).reshape(2,3)

print('list(b): ',list(b))
print('b.tolist(): ', b.tolist()) #巢狀Array轉換成巢狀list

list(a):  [3, 3, 4, 9, 1, 4]
a.tolist():  [3, 3, 4, 9, 1, 4]
list(b):  [array([4, 8, 3]), array([1, 7, 1])]
b.tolist():  [[4, 8, 3], [1, 7, 1]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [8]:
# 記得先 Import 正確的套件
import numpy as np

In [9]:

a = np.random.randint(10, size=6) 

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

print(len(a))
print(type(a))

[6 8 4 9 2 1]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [10]:
b = np.random.randint(10, size=(3,4)) 

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

print(len(b))
print(type(b))

[[3 6 7 5]
 [1 5 0 2]
 [2 7 5 2]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [11]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)

print(len(c))
print(type(c))

[[[2 4]
  [7 5]
  [9 2]]

 [[0 1]
  [0 3]
  [4 1]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [12]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable :
        newlist.append(tolist(obj))
    return list (newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 8, 4, 9, 2, 1]
[[3, 6, 7, 5], [1, 5, 0, 2], [2, 7, 5, 2]]
[[[2, 4], [7, 5], [9, 2]], [[0, 1], [0, 3], [4, 1]]]


In [14]:
## 進階版

def tolist(x) :
    if type(x) != np.ndarray :
        return x
    return [tolist(y) for y in x]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 8, 4, 9, 2, 1]
[[3, 6, 7, 5], [1, 5, 0, 2], [2, 7, 5, 2]]
[[[2, 4], [7, 5], [9, 2]], [[0, 1], [0, 3], [4, 1]]]
