# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
import numpy as np

#產出真正為0的舉證，決定內容為0時
print(np.zeros((2,3)))

#產出接近0的舉證，尚未決定內容想先初始化時使用
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [5]:
# 記得先 Import 正確的套件

import numpy as np


In [7]:
# 參考解答

a = np.random.rand(2, 3)
print(a)
print(a.round())
print(np.around(a))

[[0.23759773 0.45082007 0.99589198]
 [0.43038012 0.74787264 0.0198187 ]]
[[0. 0. 1.]
 [0. 1. 0.]]
[[0. 0. 1.]
 [0. 1. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [11]:
m = 20
n = 40

a = np.random.rand(2,3) * (n-m)
b = a

print((a-b%1 ) + m)

[[38. 37. 38.]
 [24. 28. 22.]]
