# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
# a.sum（） 對序列進行求和
# np.sum(a)可實現行和列的求和
# sum(a)可實現對行和列的求和

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
import numpy as np

In [3]:
from sklearn import preprocessing

A = np.random.random((5, 5))

print(preprocessing.scale(A))

[[-0.41658237 -0.59847867  1.44890205 -1.54530604 -0.80951862]
 [-1.58766607  0.48775552 -1.51180864  0.81683493  1.31016313]
 [ 1.45142867 -0.80935682  0.1313389   0.91809996 -1.36161856]
 [ 0.4286031  -0.82945329 -0.57989283 -0.83099471  0.87965788]
 [ 0.12421668  1.74953325  0.51146053  0.64136587 -0.01868382]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [5]:
a = np.random.random(10)
b = []

for i in a:
    if i == max(a):
        b.append(-1)
    else:
        b.append(i)

print(b)

[0.29252914084944304, 0.38667362982853404, 0.8176286667201609, 0.5108230432017764, 0.8100460983237922, 0.25708999595337756, -1, 0.5155409511979969, 0.771103324105513, 0.2987127541332508]
